account/urls.py
from django.urls import path
from . import views
# from django.contrib.auth import views as auth_views

app_name = 'account'

urlpatterns = [
    path('auth_reset_pass', views.auth_reset_pass, name='auth_reset_pass'),
    path('finduser', views.find_user, name='finduser'),
    path('send_mail', views.send_mail, name='send_mail'),
    path('find', views.find, name='find'),
    path('reset_pass', views.reset_pass, name='reset_pass'),
    path('signin', views.signin, name='signin'),
    path('signup', views.signup, name = 'signup'),
    path('update/<int:num>', views.update, name = 'update'),
    path('signout', views.signout, name="signout"),
    path('unsign/<int:num>', views.unsign, name="unsign")
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('scheduler.urls')),
    path('common/', include('account.urls')),
    path('room/', include('room.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

room/urls.py
from django.urls import path
from . import views

app_name = 'room'

urlpatterns = [
    path('room', views.create, name='create'),
    path('room/<int:room_num>', views.edit, name='edit'),
    path('room/del/<int:room_num>', views.delete, name='delete'),
    path('join/<int:room_num>', views.join_room, name='join'),
    path('out/<int:room_num>', views.out_room, name='out'),
    path('enter/<int:room_num>', views.enter_room, name='enter'),
]

scheduler/urls.py
from django.urls import path
from . import views

app_name = 'scheduler'

urlpatterns = [
    path('create/', views.create, name = 'schedule_create'),
    path('list/', views.list, name = 'schedule_list'),
    path('list/<int:schedule_num>/', views.detail, name = 'schedule_detail'),
    path('list/update/<int:schedule_num>/', views.update, name = 'schedule_update'),
    path('list/delete/<int:schedule_num>/', views.delete, name = 'schedule_delete'),
    # ----------------------------------------------------------------------------
    path('', views.index, name = 'index'), # 첫 화면 일정 리스트
    path('schedule/', views.schedule, name = 'schedule'), # 달력 스케줄
    # ----------------------------------------------------------------------------
    # path('test/', views.test, name = 'test'), # 달력 스케줄
    path('calendar_list/<int:num>/', views.calendar_list, name = 'calendar_list'), # 달력 스케줄
]

scheduler/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class User(models.Model):
    num = models.AutoField(primary_key=True)
    # primary_key를 지정해줘야 ~~.id field error가 나지 않는다.
    profile = models.ImageField(upload_to="", null=True, blank=True)
    nickname = models.CharField(max_length=45, null=False, unique=True)
    email = models.CharField(max_length=45, null=False)
    password = models.CharField(max_length=45, null=False, blank=True)
    regdate = models.DateTimeField('created', default=timezone.now, editable=False, null=False, blank=False)
    updates = models.DateTimeField('updated', default=timezone.now, editable=False, null=False, blank=False)
    
class Room(models.Model):
    num = models.AutoField(primary_key=True)
    master = models.IntegerField(null=False)
    title = models.CharField(max_length=45, null=False)
    regdate = models.DateTimeField('created', default=timezone.now, editable=False, null=False, blank=False)
    updates = models.DateTimeField('updated', default=timezone.now, editable=False, null=False, blank=False)
    
class UserInRoom(models.Model):
    num = models.AutoField(primary_key=True)
    room_num = models.ForeignKey(Room, on_delete=models.CASCADE, db_column='room_num')
    user_num = models.ForeignKey(User, on_delete=models.CASCADE, db_column='user_num')
    regdate = models.DateTimeField('created', default=timezone.now, editable=False, null=False, blank=False)
    updates = models.DateTimeField('updated', default=timezone.now, editable=False, null=False, blank=False)
    
class Calendar(models.Model):
    num = models.AutoField(primary_key=True)
    room_num = models.ForeignKey(Room, on_delete=models.CASCADE, db_column='room_num')
    user_num = models.IntegerField(null=False)
    category = models.CharField(max_length=45, null=False)
    title = models.CharField(max_length=50, null=False)
    schedule = models.TextField(blank=True, null=True)
    coworker = models.CharField(max_length=200, null=False)
    start_date = models.DateTimeField('start', null=False, blank=False)
    end_date = models.DateTimeField('end', null=False, blank=False)
    regdate = models.DateTimeField('created', default=timezone.now, editable=False, null=False, blank=False)
    updates = models.DateTimeField('updated', default=timezone.now, editable=False, null=False, blank=False)

scheduler/forms.py
from django.forms import CharField, DateInput, DateTimeInput, EmailInput, FileInput, ImageField, ModelForm, PasswordInput, TextInput, Textarea, ValidationError
from .models import *

class UserForm(ModelForm):
    profile = ImageField(required=False, widget=FileInput(attrs={'type': 'file'}))
    password = CharField(required=False, widget=PasswordInput(attrs={'type': 'password', 'autocomplete': 'current-password'}))
    
    class Meta:
        model = User
        fields = [
            'profile', 'nickname', 'email', 'password'
            ]
        widgets = {
            'email': EmailInput(attrs={'autocomplete': 'username'}),
        }
        
class LoginForm(ModelForm):
    # email = forms.CharField(required=False)
    
    def clean_email(self):
        data = self.cleaned_data['email']
        if "@" not in data:
            raise ValidationError("이메일 형식과 다릅니다.")

        # Always return a value to use as the new cleaned data, even if
        # this method didn't change it.
        return data
    
    class Meta:
        model = User
        fields = [
            'email', 'password'
            ]
        widgets = {
            'email': EmailInput(attrs={'type':'email', 'autocomplete':'username'}),
            'password': PasswordInput(attrs={'type':'password', 'autocomplete':'current-password'})
        }
        
class FindForm(ModelForm):
    def clean_email(self):
        data = self.cleaned_data['email']
        if "@" not in data:
            raise ValidationError("이메일 형식과 다릅니다.")

        return data
    
    class Meta:
        model = User
        fields = [
            'nickname', 'email'#, 'password'
            ]
        
class CheckForm(ModelForm):
    def clean_email(self):
        data = self.cleaned_data['email']
        if "@" not in data:
            raise ValidationError("이메일 형식과 다릅니다.")

        return data
    
    class Meta:
        model = User
        fields = [
            'email'#, 'password'
            ]
    
class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = [
            'title'
            ]

class UserInRoomForm(ModelForm):
    class Meta:
        model = UserInRoom
        fields = [
            'room_num', 'user_num'
            ]

class CalendarForm(ModelForm):
    class Meta:
        model = Calendar
        fields = [
            'category', 'title', 'schedule', 'coworker', 'start_date', 'end_date'#, 'room_num', 'user_num', 
            ]
        widgets = {
            # 'room_num': TextInput(attrs={'ghost':''}),
            # 'user_num': TextInput(attrs={'ghost':''}),
            'schedule': Textarea(attrs={'rows': 10}),
            'start_date': DateTimeInput(attrs={'type': 'datetime-local'}),
            'end_date': DateTimeInput(attrs={'type': 'datetime-local'}),
        }
    # def clean_coworker(self):
    #     data = self.cleaned_data['coworker']
    #     if "," in data:
    #         raise forms.ValidationError("콤마 멈춰!")

    #     return data

scheduler/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
# from django.utils import timezone
from rest_framework.decorators import api_view
from .forms import CalendarForm
from .models import User, Room, Calendar
from django.core import serializers
from django.http import JsonResponse, HttpResponse

# from django.contrib.auth import views as auth_views

def path_type(request):
    if request.path.split('/')[-1] == '':
        return 'Home'
    elif request.path.split('/')[-1] == 'schedule':
        return 'Schedule'
    
@api_view(['GET'])
def index(request):
    room_list = Room.objects.order_by('regdate')
    context = {
        'path_type': path_type(request),
        'room_list': room_list,
    }
    
    return render(request, 'scheduler/index.html', context)

@api_view(['GET'])
def schedule(request):
    user = User.objects.all()

    context = {
        'path_type': path_type(request),
        'schedule': user
    }

    return render(request, 'scheduler/schedule.html', context)

def calendar_list(reqeust, num):
    '''
    schedule 목록
    '''
    schedule_list = Calendar.objects.filter(room_num_id=num).order_by('regdate')
    
    # 밑에 과정들
    # https://dev-yakuza.posstree.com/ko/django/response-model-to-json/ [ 참조 ]
    
    list = serializers.serialize('json', schedule_list)
    return HttpResponse(list, content_type="text/json-comment-filtered")

def list(reqeust):
    '''
    schedule 목록
    '''
    schedule_list = Calendar.objects.order_by('regdate')
    context = {'schedule_list': schedule_list}
    return render(reqeust, 'scheduler/scheduler/list.html', context)

def create(request):
    '''
    schedule 등록
    '''
    if request.method == 'POST':
        form = CalendarForm(request.POST)
        if form.is_valid():
            calendar = form.save(commit=False)
            
            # modelForm에 해당되지 않는 필드는 자동 할당되지 않는다.
            # 수동으로 할당해야하고, 그러지 않으면 null값을 할당한다.
            calendar.room_num_id = request.POST['room_num']
            calendar.user_num = request.POST['user_num']
            
            calendar.start_date = str(calendar.start_date).replace('+09:00','+00:00')
            calendar.end_date = str(calendar.end_date).replace('+09:00','+00:00')
            
            calendar.save()
            
            return redirect ('room:enter', room_num=calendar.room_num_id)
    else:
        form = CalendarForm()
    context = {'form': form}
    return render(request, 'scheduler/scheduler/create.html', context)

def detail(request, schedule_num):
    '''
    schedule 내용 출력
    '''
    schedule = Calendar.objects.filter(pk=schedule_num).get(pk=schedule_num)
    context = {'schedule': schedule}
    return render(request, 'scheduler/scheduler/detail.html', context)

def update(request, schedule_num):
    '''
    schedule 내용 수정
    '''
    calendar = Calendar.objects.filter(pk=schedule_num).get(pk=schedule_num)
    if request.method == 'POST':
        form = CalendarForm(request.POST, instance=calendar)
        if form.is_valid():
            calendar = form.save(commit=False)
            calendar.save()
            return redirect ('room:enter', room_num=calendar.room_num_id)
    else:
        form = CalendarForm(instance=calendar)
    print(calendar.start_date)
    context = {'form': form, 'calendar':calendar}
    return render(request, 'scheduler/scheduler/update.html', context)

@api_view(['POST'])
def delete(request, schedule_num):
    '''
    schedule 삭제
    '''
    cal = Calendar.objects.filter(pk=schedule_num)
    
    room_num = cal[0].room_num_id
    
    cal.delete()
    
    return redirect('room:enter', room_num=room_num)

scheduler/templates/scheduler/find.html
{% extends './layout.html' %}
{% load bootstrap5 %}
{% block content %}
<div class="container-xl px-4">
    <div class="row justify-content-center">
        <div class="col-xl-5 col-lg-6 col-md-8 col-sm-11">
            <!-- Social login form-->
            <div class="card my-5">
                <div class="card-body p-5 text-center">
                    <div class="h3 fw-light mb-3">Find Account</div>
                </div>
                <hr class="my-0">
                <div class="card-body p-5">
                    <!-- Login form-->
                    <form method="post" action="{% url 'account:find' %}" novalidate>
                        {% include "./form_errors.html" %}
                        {% csrf_token %}
                        {% bootstrap_form findForm %}
                        <button class="btn btn-info">찾기</button>
                        {% if request.GET.success == '4' %}
                        <a class="btn btn-success" href="{% url 'account:reset_pass' %}">변경</a>
                        {% endif %}
                    </form>
                </div>
                <hr class="my-0">
                <div class="card-body px-5 py-4">
                    <div class="small text-center">
                        New user?
                        <a href="{% url 'account:signup' %}">Create an account!</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% comment %} Metropolis font {% endcomment %}

scheduler/templates/scheduler/form_errors.html
{% if request.GET.error == '1' %}
    <div class="alert alert-danger">
        <strong>!</strong>
        사용자 이메일과 비밀번호를 다시 확인해 주세요.
    </div>
{% endif %}
{% if request.GET.error == '2' %}
    <div class="alert alert-danger">
        <strong>!</strong>
        닉네임과 이메일 중 일치하는 정보가 없습니다.
    </div>
{% endif %}
{% if request.GET.error == '3' %}
    <div class="alert alert-danger">
        <strong>!</strong>
        이메일 형식이 틀립니다.
    </div>
{% endif %}
{% if request.GET.success == '4' %}
    <div class="alert alert-success">
        <strong>!</strong>
        닉네임과 이메일 중 일치하는 정보가 있습니다. 비밀번호를 변경하시려면 아래의 변경 버튼을 클릭해주세요.
    </div>
{% endif %}

scheduler/templates/scheduler/index.html
{% extends './layout.html' %}
{% load customs %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <!-- column -->
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <!-- title -->
                    <div class="d-md-flex justify-content-between">
                        <div>
                            {% if request.session.sign %}
                            {% set request.session.sign|user_in_room_count as room_count %}
                            {% set request.session.sign|user_nickname as nickname %}
                            <h4 class="card-title">현재 {{nickname}}님이 공유 중인 스케쥴러</h4>
                            {% if room_count > 0 %}
                            <h5 class="card-subtitle">{{nickname}}님은 {{room_count}}개 스케쥴러에 참여 중입니다.
                            </h5>
                            {% else %}
                            <h5 class="card-subtitle">아직 참여한 스케쥴러가 없습니다.</h5>
                            {% endif %}
                            {% else %}
                            <h4 class="card-title">공유 스케쥴러입니다.</h4>
                            <h5 class="card-subtitle">팀과 함께 스케쥴러에 참여 해보세요😉</h5>
                            {% endif %}
                        </div>
                        {% comment %} <div class="ms-auto">
                            <div class="dl">
                                <select class="form-select shadow-none">
                                    <option value="0" selected>Monthly</option>
                                    <option value="1">Daily</option>
                                    <option value="2">Weekly</option>
                                    <option value="3">Yearly</option>
                                </select>
                            </div>
                        </div> {% endcomment %}
                        {% if request.session.sign %}
                        <div class="ms-3">
                            <a class="btn btn-info" href="{% url 'room:create' %}">방 생성</a>
                        </div>
                        {% endif %}
                    </div>
                    <!-- title -->
                    <div class="table-responsive">
                        <table class="table mb-0 table-hover align-middle text-nowrap">
                            <thead>
                                <tr>
                                    <th class="border-top-0">방 이름</th>
                                    <th class="border-top-0">인원</th>
                                    <th class="border-top-0">방장</th>
                                    <th class="border-top-0">옵션</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for room in room_list %}
                                {% set room.master|find_user as user %}
                                <tr>
                                    <td>
                                        <div class="d-flex align-items-center">
                                            <div class="m-r-10">
                                                <a class="btn btn-circle d-flex btn-info text-white">{{user.nickname|first_word|upper}}</a>
                                            </div>
                                            <div class="">
                                                <h4 class="m-b-0 font-16 fw-bold">{{room.title}}</h4>
                                            </div>
                                        </div>
                                    </td>

                                    {% with room.num|user_count as count %}
                                    <td>{{count}}</td>
                                    {% endwith %}

                                    {% with room.master|find_user as user %}
                                    <td>
                                        <label class="badge bg-danger">{{user.nickname|capitalize}}</label>
                                    </td>
                                    {% endwith %}
                                    <td>
                                        {% if request.session.sign == room.master %}
                                        <a href="{% url 'room:enter' room_num=room.num %}" class="btn btn-success">👈
                                            Enter</a>
                                        <a href="{% url 'room:edit' room_num=room.num %}"
                                            class="btn btn-success">🛠️</a>
                                        <form class="d-inline-block" action="{% url 'room:delete' room_num=room.num %}"
                                            method="post">
                                            <button class="btn btn-danger">🗑️</button>
                                        </form>
                                        {% else %}
                                        {% if room.num|is_crew:request.session.sign %}
                                        <a href="{% url 'room:enter' room_num=room.num %}" class="btn btn-success">👈
                                            Enter</a>
                                        <form class="d-inline-block" action="{% url 'room:out' room_num=room.num %}"
                                            method="post">
                                            <input type="hidden" name="user_num" value="{{request.session.sign.num}}">
                                            <button type="submit" class="btn btn-danger">👋 Out</button>
                                        </form>
                                        {% else %}
                                        {% if request.session.sign %}
                                        <form class="d-inline-block" action="{% url 'room:join' room_num=room.num %}"
                                            method="post">
                                            <input type="hidden" name="user_num" value="{{request.session.sign.num}}">
                                            <button type="submit" class="btn btn-info">👈 Join the room</button>
                                        </form>
                                        {% else %}
                                        <button onclick="alert('로그인이 필요합니다.')" class="btn btn-info">👈 Join the
                                            room</button>
                                        {% endif %}
                                        {% endif %}
                                        {% endif %}
                                    </td>
                                </tr>
                                {% empty %}
                                <tr>
                                    <td colspan="4">
                                        <div class="alert alert-warning">
                                            참여한 방이 없습니다 😥
                                        </div>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

scheduler/templates/scheduler/layout.html
{% load static %}

<!DOCTYPE html>
<html dir="ltr" lang="ko">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords"
        content="wrappixel, admin dashboard, html css dashboard, web dashboard, bootstrap 5 admin, bootstrap 5, css3 dashboard, bootstrap 5 dashboard, Flexy lite admin bootstrap 5 dashboard, frontend, responsive bootstrap 5 admin template, Flexy admin lite design, Flexy admin lite dashboard bootstrap 5 dashboard template">
    <meta name="description"
        content="Flexy Admin Lite is powerful and clean admin dashboard template, inpired from Bootstrap Framework">
    <meta name="robots" content="noindex,nofollow">
    <title>Co-Scheduler</title>
    
    {% include './common/load-styles.html' %}
</head>

<body>
    <div class="preloader">
        <div class="lds-ripple">
            <div class="lds-pos"></div>
            <div class="lds-pos"></div>
        </div>
    </div>

    <div id="main-wrapper" data-layout="vertical" data-navbarbg="skin5" data-sidebartype="full"
        data-sidebar-position="absolute" data-header-position="absolute" data-boxed-layout="full">
        {% include './common/nav.html' %}
        
        {% include './common/aside.html' %}
        
        <div class="page-wrapper">
            {% include './common/breadcrumb.html' %}
            {% block content %}
            {% endblock %}
        </div>
    </div>
    {% include './common/load-scripts.html' %}
    <div hidden class="amp-pxl mt-4" style="height: 350px;">
        <div class="chartist-tooltip"></div>
    </div>
    {% include './deco/sign_success.html' %}
    {% include './common/toast.html' %}
</body>

</html>

scheduler/templates/scheduler/reset_pass.html
{% extends './layout.html' %}
{% load bootstrap5 %}
{% block content %}
<div class="container-xl px-4">
    <div class="row justify-content-center">
        <div class="col-xl-5 col-lg-6 col-md-8 col-sm-11">
            <!-- Social login form-->
            <div class="card my-5">
                <div class="card-body p-5 text-center">
                    <div class="h3 fw-light mb-3">Check Account</div>
                </div>
                <hr class="my-0">
                <div class="card-body p-5">
                    {% if request.GET.check == '1' %}
                    <div class="alert alert-success">
                        메일이 발송되었습니다. 메일을 확인 한 후 인증 절차에 맞게 진행해주세요.
                    </div>
                    {% else %}
                    <!-- Login form-->
                    <form method="post" action="{% url 'account:send_mail' %}" novalidate>
                        {% include "./form_errors.html" %}
                        {% csrf_token %}
                        {% bootstrap_form checkForm %}
                        <button class="btn btn-info">인증 메일 보내기</button>
                    </form>
                    {% endif %}
                </div>
                <hr class="my-0">
                <div class="card-body px-5 py-4">
                    <div class="small text-center">
                        New user?
                        <a href="{% url 'account:signup' %}">Create an account!</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% comment %} Metropolis font {% endcomment %}

scheduler/templates/scheduler/schedule.html
{% extends './layout.html' %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div id="calendar"></div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

scheduler/templates/scheduler/signin.html
{% extends './layout.html' %}
{% load bootstrap5 %}
{% block content %}
<div class="container-xl px-4">
    <div class="row justify-content-center">
        <div class="col-xl-5 col-lg-6 col-md-8 col-sm-11">
            <!-- Social login form-->
            <div class="card my-5">
                <div class="card-body p-5 text-center">
                    <div class="h3 fw-light mb-3">Sign In</div>
                </div>
                <hr class="my-0">
                <div class="card-body p-5">
                    <!-- Login form-->
                    <form method="post" action="{% url 'account:signin' %}" novalidate>
                        {% include "./form_errors.html" %}
                        {% csrf_token %}
                        <!-- Form Group (email address)-->
                        {% bootstrap_field form.email %}
                        
                        <!-- Form Group (password)-->
                        {% bootstrap_field form.password %}

                        <!-- Form Group (forgot password link)-->
                        <div class="mb-3">
                            <a class="small" href="{% url 'account:find' %}">Forgot your password?</a>
                        </div>
                        <!-- Form Group (login box)-->
                        <div class="d-flex align-items-center justify-content-between mb-0">
                            <div class="form-check">
                                <input class="form-check-input" id="checkRememberPassword" type="checkbox" value="">
                                <label class="form-check-label" for="checkRememberPassword">Remember password</label>
                            </div>
                            <button class="btn btn-primary">Login</button>
                        </div>
                    </form>
                </div>
                <hr class="my-0">
                <div class="card-body px-5 py-4">
                    <div class="small text-center">
                        New user?
                        <a href="{% url 'account:signup' %}">Create an account!</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% comment %} Metropolis font {% endcomment %}

scheduler/templates/scheduler/signup.html
{% extends './layout.html' %}
{% load customs %}
{% load bootstrap5 %}

{% block content %}

{% set request.session.sign|user_profile:'http://placehold.jp/150x150.png' as profile %}
{% set request.session.sign|user_nickname:'No Name' as nickname %}
{% firstof '' request.session.sign|user_email as email %}

<div class="container-fluid">
    <!-- Row -->
    <div class="row">
        <!-- Column -->
        <div class="col-12">
            <div class="card">
                <form class="form-horizontal form-material" action="{% if request.session.sign %}{% url 'account:update' num=request.session.sign %}{% else %}{% url 'account:signup' %}{% endif %}" method="post" enctype="multipart/form-data" novalidate>
                    {% csrf_token %}
                    <div class="card-body">
                        <div class="m-t-30 text-center">
                            <label for="profile">
                                <img id="relProfile" src="{{profile}}" class="rounded-circle" width="150" height="150" />
                            </label>
                            <input ghost type="file" name="profile" id="profile">
                            <h4 id="relNickname" class="card-title m-t-10">{{nickname}}</h4>
                        </div>
                    </div>
                    <div>
                        <hr>
                    </div>
                    <div class="card-body">

                        {% bootstrap_form userForm %}
                        
                        <div class="form-group">
                            <div class="col-sm-12">
                                {% if request.session.sign %}
                                <button class="btn btn-success text-white">Update</button>
                                <button class="btn btn-danger text-white" id="unsign" dir="{% url 'account:unsign' num=request.session.sign %}" type="button">Un Sign</button>
                                {% else %}
                                <button class="btn btn-success text-white">Sign Up</button>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </form>
                
            </div>
        </div>
        <!-- Column -->
    </div>
</div>
{% endblock %}