project_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('scheduler.urls')),
    path('common/', include('account.urls')),
    path('room/', include('room.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

room/urls.py
from django.urls import path
from . import views

app_name = 'room'

urlpatterns = [
    path('room', views.create, name='create'),
    path('room/<int:room_num>', views.edit, name='edit'),
    path('room/del/<int:room_num>', views.delete, name='delete'),
    path('join/<int:room_num>', views.join_room, name='join'),
    path('out/<int:room_num>', views.out_room, name='out'),
    path('enter/<int:room_num>', views.enter_room, name='enter'),
]

scheduler/urls.py
from django.urls import path
from . import views

app_name = 'scheduler'

urlpatterns = [
    path('create/', views.create, name = 'schedule_create'),
    path('list/', views.list, name = 'schedule_list'),
    path('list/<int:schedule_num>/', views.detail, name = 'schedule_detail'),
    path('list/update/<int:schedule_num>/', views.update, name = 'schedule_update'),
    path('list/delete/<int:schedule_num>/', views.delete, name = 'schedule_delete'),
    # ----------------------------------------------------------------------------
    path('', views.index, name = 'index'), # 첫 화면 일정 리스트
    path('schedule/', views.schedule, name = 'schedule'), # 달력 스케줄
    # ----------------------------------------------------------------------------
    # path('test/', views.test, name = 'test'), # 달력 스케줄
    path('calendar_list/<int:num>/', views.calendar_list, name = 'calendar_list'), # 달력 스케줄
]

scheduler/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class User(models.Model):
    num = models.AutoField(primary_key=True)
    # primary_key를 지정해줘야 ~~.id field error가 나지 않는다.
    profile = models.ImageField(upload_to="", null=True, blank=True)
    nickname = models.CharField(max_length=45, null=False, unique=True)
    email = models.CharField(max_length=45, null=False)
    password = models.CharField(max_length=45, null=False, blank=True)
    regdate = models.DateTimeField('created', default=timezone.now, editable=False, null=False, blank=False)
    updates = models.DateTimeField('updated', default=timezone.now, editable=False, null=False, blank=False)
    
class Room(models.Model):
    num = models.AutoField(primary_key=True)
    master = models.IntegerField(null=False)
    title = models.CharField(max_length=45, null=False)
    regdate = models.DateTimeField('created', default=timezone.now, editable=False, null=False, blank=False)
    updates = models.DateTimeField('updated', default=timezone.now, editable=False, null=False, blank=False)
    
class UserInRoom(models.Model):
    num = models.AutoField(primary_key=True)
    room_num = models.ForeignKey(Room, on_delete=models.CASCADE, db_column='room_num')
    user_num = models.ForeignKey(User, on_delete=models.CASCADE, db_column='user_num')
    regdate = models.DateTimeField('created', default=timezone.now, editable=False, null=False, blank=False)
    updates = models.DateTimeField('updated', default=timezone.now, editable=False, null=False, blank=False)
    
class Calendar(models.Model):
    num = models.AutoField(primary_key=True)
    room_num = models.ForeignKey(Room, on_delete=models.CASCADE, db_column='room_num')
    user_num = models.IntegerField(null=False)
    category = models.CharField(max_length=45, null=False)
    title = models.CharField(max_length=50, null=False)
    schedule = models.TextField(blank=True, null=True)
    coworker = models.CharField(max_length=200, null=False)
    start_date = models.DateTimeField('start', null=False, blank=False)
    end_date = models.DateTimeField('end', null=False, blank=False)
    regdate = models.DateTimeField('created', default=timezone.now, editable=False, null=False, blank=False)
    updates = models.DateTimeField('updated', default=timezone.now, editable=False, null=False, blank=False)

scheduler/forms.py
from django.forms import CharField, DateInput, DateTimeInput, EmailInput, FileInput, ImageField, ModelForm, PasswordInput, TextInput, Textarea, ValidationError
from .models import *

class UserForm(ModelForm):
    profile = ImageField(required=False, widget=FileInput(attrs={'type': 'file'}))
    password = CharField(required=False, widget=PasswordInput(attrs={'type': 'password', 'autocomplete': 'current-password'}))
    
    class Meta:
        model = User
        fields = [
            'profile', 'nickname', 'email', 'password'
            ]
        widgets = {
            'email': EmailInput(attrs={'autocomplete': 'username'}),
        }
        
class LoginForm(ModelForm):
    # email = forms.CharField(required=False)
    
    def clean_email(self):
        data = self.cleaned_data['email']
        if "@" not in data:
            raise ValidationError("이메일 형식과 다릅니다.")

        # Always return a value to use as the new cleaned data, even if
        # this method didn't change it.
        return data
    
    class Meta:
        model = User
        fields = [
            'email', 'password'
            ]
        widgets = {
            'email': EmailInput(attrs={'type':'email', 'autocomplete':'username'}),
            'password': PasswordInput(attrs={'type':'password', 'autocomplete':'current-password'})
        }
        
class FindForm(ModelForm):
    def clean_email(self):
        data = self.cleaned_data['email']
        if "@" not in data:
            raise ValidationError("이메일 형식과 다릅니다.")

        return data
    
    class Meta:
        model = User
        fields = [
            'nickname', 'email'#, 'password'
            ]
        
class CheckForm(ModelForm):
    def clean_email(self):
        data = self.cleaned_data['email']
        if "@" not in data:
            raise ValidationError("이메일 형식과 다릅니다.")

        return data
    
    class Meta:
        model = User
        fields = [
            'email'#, 'password'
            ]
    
class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = [
            'title'
            ]

class UserInRoomForm(ModelForm):
    class Meta:
        model = UserInRoom
        fields = [
            'room_num', 'user_num'
            ]

class CalendarForm(ModelForm):
    class Meta:
        model = Calendar
        fields = [
            'category', 'title', 'schedule', 'coworker', 'start_date', 'end_date'#, 'room_num', 'user_num', 
            ]
        widgets = {
            # 'room_num': TextInput(attrs={'ghost':''}),
            # 'user_num': TextInput(attrs={'ghost':''}),
            'schedule': Textarea(attrs={'rows': 10}),
            'start_date': DateTimeInput(attrs={'type': 'datetime-local'}),
            'end_date': DateTimeInput(attrs={'type': 'datetime-local'}),
        }
    # def clean_coworker(self):
    #     data = self.cleaned_data['coworker']
    #     if "," in data:
    #         raise forms.ValidationError("콤마 멈춰!")

    #     return data

scheduler/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
# from django.utils import timezone
from rest_framework.decorators import api_view
from .forms import CalendarForm
from .models import User, Room, Calendar
from django.core import serializers
from django.http import JsonResponse, HttpResponse

# from django.contrib.auth import views as auth_views

def path_type(request):
    if request.path.split('/')[-1] == '':
        return 'Home'
    elif request.path.split('/')[-1] == 'schedule':
        return 'Schedule'
    
@api_view(['GET'])
def index(request):
    room_list = Room.objects.order_by('regdate')
    context = {
        'path_type': path_type(request),
        'room_list': room_list,
    }
    
    return render(request, 'scheduler/index.html', context)

@api_view(['GET'])
def schedule(request):
    user = User.objects.all()

    context = {
        'path_type': path_type(request),
        'schedule': user
    }

    return render(request, 'scheduler/schedule.html', context)

def calendar_list(reqeust, num):
    '''
    schedule 목록
    '''
    schedule_list = Calendar.objects.filter(room_num_id=num).order_by('regdate')
    
    # 밑에 과정들
    # https://dev-yakuza.posstree.com/ko/django/response-model-to-json/ [ 참조 ]
    
    list = serializers.serialize('json', schedule_list)
    return HttpResponse(list, content_type="text/json-comment-filtered")

def list(reqeust):
    '''
    schedule 목록
    '''
    schedule_list = Calendar.objects.order_by('regdate')
    context = {'schedule_list': schedule_list}
    return render(reqeust, 'scheduler/scheduler/list.html', context)

def create(request):
    '''
    schedule 등록
    '''
    if request.method == 'POST':
        form = CalendarForm(request.POST)
        if form.is_valid():
            calendar = form.save(commit=False)
            
            # modelForm에 해당되지 않는 필드는 자동 할당되지 않는다.
            # 수동으로 할당해야하고, 그러지 않으면 null값을 할당한다.
            calendar.room_num_id = request.POST['room_num']
            calendar.user_num = request.POST['user_num']
            
            calendar.start_date = str(calendar.start_date).replace('+09:00','+00:00')
            calendar.end_date = str(calendar.end_date).replace('+09:00','+00:00')
            
            calendar.save()
            
            return redirect ('room:enter', room_num=calendar.room_num_id)
    else:
        form = CalendarForm()
    context = {'form': form}
    return render(request, 'scheduler/scheduler/create.html', context)

def detail(request, schedule_num):
    '''
    schedule 내용 출력
    '''
    schedule = Calendar.objects.filter(pk=schedule_num).get(pk=schedule_num)
    context = {'schedule': schedule}
    return render(request, 'scheduler/scheduler/detail.html', context)

def update(request, schedule_num):
    '''
    schedule 내용 수정
    '''
    calendar = Calendar.objects.filter(pk=schedule_num).get(pk=schedule_num)
    if request.method == 'POST':
        form = CalendarForm(request.POST, instance=calendar)
        if form.is_valid():
            calendar = form.save(commit=False)
            calendar.save()
            return redirect ('room:enter', room_num=calendar.room_num_id)
    else:
        form = CalendarForm(instance=calendar)
    print(calendar.start_date)
    context = {'form': form, 'calendar':calendar}
    return render(request, 'scheduler/scheduler/update.html', context)

@api_view(['POST'])
def delete(request, schedule_num):
    '''
    schedule 삭제
    '''
    cal = Calendar.objects.filter(pk=schedule_num)
    
    room_num = cal[0].room_num_id
    
    cal.delete()
    
    return redirect('room:enter', room_num=room_num)

scheduler/templates/scheduler/scheduler/create.html
{% extends '../layout.html' %}
{% load bootstrap5 %}
{% load customs %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">일정 등록</h5>
    <form method="post" class="post-form my-3" novalidate>
        {% csrf_token %}
        {% set 'start_date/'|add:request.GET.s as start_date %}
        {% set 'end_date/'|add:request.GET.e as end_date %}
        {% bootstrap_form form|form_value:start_date|form_value:end_date  %}
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>

<script>
    const rnum = document.getElementById('id_room_num');
    const unum = document.getElementById('id_user_num');

    rnum.value = '{{request.GET.r_num}}';
    unum.value = "{{request.session.sign}}";
</script>
{% endblock content %}

scheduler/templates/scheduler/scheduler/detail.html
{% extends '../layout.html' %}
{% load bootstrap5 %}
{% block content %}

<div class="container my-3">
    <h2 class="py2">num: {{ schedule.num }}</h2>
    <h2 class="py2">room_num: {{ schedule.room_num }}</h2>
    <h2 class="py2">user_num: {{ schedule.user_num }}</h2>
    <h2 class="py2">분류: {{ schedule.category }}</h2>
    <h2 class="py2">제목: {{ schedule.title }}</h2>
    <h2 class="py2">일정 내용: {{ schedule.schedule }}</h2>
    <h2 class="py2">동료: {{ schedule.coworker }}</h2>
    <h2 class="py2">시작일: {{ schedule.start_date }}</h2>
    <h2 class="py2">종료일: {{ schedule.end_date }}</h2>
    <h2 class="py2">최종 수정일: {{ schedule.updates }}</h2>
    
    <div class="my-3">
        <a href="{% url 'scheduler:schedule_update' schedule.num %}" class="btn btn-sm btn-outline-secondary">수정</a>
        <a href="{% url 'scheduler:schedule_delete' schedule.num %}" class="delete btn btn-sm btn-outline-secondary">삭제</a>
    </div>
</div>

{% endblock content %}

scheduler/templates/scheduler/scheduler/list.html
{% extends '../layout.html' %}
{% load bootstrap5 %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
            <tr class="thead-dark">
                <th>no.</th>
                <th>category</th>
                <th>title</th>
                <th>start_date</th>
                <th>end_date</th>
                <th>updates</th>
            </tr>
        </thead>
        <tbody>
            {% if schedule_list %}
            {% for schedule in schedule_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ schedule.category }}</td>
                <td><a href="{% url 'scheduler:schedule_detail' schedule.num %}">{{ schedule.title }}</a></td>
                <td>{{ schedule.start_date }}</td>
                <td>{{ schedule.end_date }}</td>
                <td>{{ schedule.updates }}</td>
            </tr>
            {% endfor %}
            {% else %} 
            <tr>
                <td colspan="3">일정이 없습니다.</td>
            </tr>
            {% endif %}
        </tbody>
    </table>
    <a href="{% url 'scheduler:schedule' %}" class="btn btn-primary">일정 등록하기</a>
</div>
{% endblock content %}

scheduler/templates/scheduler/scheduler/read.html
{% extends '../layout.html' %}
{% load bootstrap5 %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
            <tr class="thead-dark">
                <th>no.</th>
                <!--<th>room_num</th>
                <th>user_num</th>-->
                <th>category</th>
                <th>title</th>
                <!--<th>schedule</th>
                <th>coworker</th>-->
                <th>start_date</th>
                <th>end_date</th>
                <!--<th>regdate</th>-->
                <th>updates</th>
            </tr>
        </thead>
        <tbody>
            {% if schedule_list %}
            {% for schedule in schedule_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <!--<td>{{ schedule.room_num }}</td>
                <td>{{ schedule.user_num }}</td>-->
                <td>{{ schedule.category }}</td>
                <td>{{ schedule.title }}</td>
                <!--<td>{{ schedule.schedule }}</td>
                <td>{{ schedule.coworker }}</td>-->
                <td>{{ schedule.start_date }}</td>
                <td>{{ schedule.end_date }}</td>
                <!--<td>{{ schedule.regdate }}</td>-->
                <td>{{ schedule.updates }}</td>
            </tr>
            {% endfor %}
            {% else %} 
            <tr>
                <td colspan="3">일정이 없습니다.</td>
            </tr>
            {% endif %}
        </tbody>
    </table>
    <a href="{% url 'scheduler:schedule_create' %}" class="btn btn-primary">일정 등록하기</a>
</div>
{% endblock content %}

scheduler/templates/scheduler/scheduler/update.html
{% extends '../layout.html' %}
{% load bootstrap5 %}
{% load customs %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">일정 등록</h5>
    <form method="post" class="post-form my-3" novalidate>
        {% csrf_token %}
        
        {% set calendar.start_date|date:'Y-m-d\TH:i' as start_date %}
        {% set calendar.end_date|date:'Y-m-d\TH:i' as end_date %}

        {% bootstrap_form form %}
        <input type="number" ghost name="room_num" value="{{request.GET.r_num}}">
        <input type="number" ghost name="user_num" value="{{request.session.sign}}">
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>

<script>
    const start = document.getElementById('id_start_date');
    const end = document.getElementById('id_end_date');

    start.value = '{{start_date}}';
    end.value = "{{end_date}}";
</script>
{% endblock content %}