project_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('scheduler.urls')),
    path('common/', include('account.urls')),
    path('room/', include('room.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

room/urls.py
from django.urls import path
from . import views

app_name = 'room'

urlpatterns = [
    path('room', views.create, name='create'),
    path('room/<int:room_num>', views.edit, name='edit'),
    path('room/del/<int:room_num>', views.delete, name='delete'),
    path('join/<int:room_num>', views.join_room, name='join'),
    path('out/<int:room_num>', views.out_room, name='out'),
    path('enter/<int:room_num>', views.enter_room, name='enter'),
]

scheduler/urls.py
from django.urls import path
from . import views

app_name = 'scheduler'

urlpatterns = [
    path('create/', views.create, name = 'schedule_create'),
    path('list/', views.list, name = 'schedule_list'),
    path('list/<int:schedule_num>/', views.detail, name = 'schedule_detail'),
    path('list/update/<int:schedule_num>/', views.update, name = 'schedule_update'),
    path('list/delete/<int:schedule_num>/', views.delete, name = 'schedule_delete'),
    # ----------------------------------------------------------------------------
    path('', views.index, name = 'index'), # 첫 화면 일정 리스트
    path('schedule/', views.schedule, name = 'schedule'), # 달력 스케줄
    # ----------------------------------------------------------------------------
    # path('test/', views.test, name = 'test'), # 달력 스케줄
    path('calendar_list/<int:num>/', views.calendar_list, name = 'calendar_list'), # 달력 스케줄
]

room/models.py
from django.db import models

# Create your models here.

scheduler/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class User(models.Model):
    num = models.AutoField(primary_key=True)
    # primary_key를 지정해줘야 ~~.id field error가 나지 않는다.
    profile = models.ImageField(upload_to="", null=True, blank=True)
    nickname = models.CharField(max_length=45, null=False, unique=True)
    email = models.CharField(max_length=45, null=False)
    password = models.CharField(max_length=45, null=False, blank=True)
    regdate = models.DateTimeField('created', default=timezone.now, editable=False, null=False, blank=False)
    updates = models.DateTimeField('updated', default=timezone.now, editable=False, null=False, blank=False)
    
class Room(models.Model):
    num = models.AutoField(primary_key=True)
    master = models.IntegerField(null=False)
    title = models.CharField(max_length=45, null=False)
    regdate = models.DateTimeField('created', default=timezone.now, editable=False, null=False, blank=False)
    updates = models.DateTimeField('updated', default=timezone.now, editable=False, null=False, blank=False)
    
class UserInRoom(models.Model):
    num = models.AutoField(primary_key=True)
    room_num = models.ForeignKey(Room, on_delete=models.CASCADE, db_column='room_num')
    user_num = models.ForeignKey(User, on_delete=models.CASCADE, db_column='user_num')
    regdate = models.DateTimeField('created', default=timezone.now, editable=False, null=False, blank=False)
    updates = models.DateTimeField('updated', default=timezone.now, editable=False, null=False, blank=False)
    
class Calendar(models.Model):
    num = models.AutoField(primary_key=True)
    room_num = models.ForeignKey(Room, on_delete=models.CASCADE, db_column='room_num')
    user_num = models.IntegerField(null=False)
    category = models.CharField(max_length=45, null=False)
    title = models.CharField(max_length=50, null=False)
    schedule = models.TextField(blank=True, null=True)
    coworker = models.CharField(max_length=200, null=False)
    start_date = models.DateTimeField('start', null=False, blank=False)
    end_date = models.DateTimeField('end', null=False, blank=False)
    regdate = models.DateTimeField('created', default=timezone.now, editable=False, null=False, blank=False)
    updates = models.DateTimeField('updated', default=timezone.now, editable=False, null=False, blank=False)

scheduler/forms.py
from django.forms import CharField, DateInput, DateTimeInput, EmailInput, FileInput, ImageField, ModelForm, PasswordInput, TextInput, Textarea, ValidationError
from .models import *

class UserForm(ModelForm):
    profile = ImageField(required=False, widget=FileInput(attrs={'type': 'file'}))
    password = CharField(required=False, widget=PasswordInput(attrs={'type': 'password', 'autocomplete': 'current-password'}))
    
    class Meta:
        model = User
        fields = [
            'profile', 'nickname', 'email', 'password'
            ]
        widgets = {
            'email': EmailInput(attrs={'autocomplete': 'username'}),
        }
        
class LoginForm(ModelForm):
    # email = forms.CharField(required=False)
    
    def clean_email(self):
        data = self.cleaned_data['email']
        if "@" not in data:
            raise ValidationError("이메일 형식과 다릅니다.")

        # Always return a value to use as the new cleaned data, even if
        # this method didn't change it.
        return data
    
    class Meta:
        model = User
        fields = [
            'email', 'password'
            ]
        widgets = {
            'email': EmailInput(attrs={'type':'email', 'autocomplete':'username'}),
            'password': PasswordInput(attrs={'type':'password', 'autocomplete':'current-password'})
        }
        
class FindForm(ModelForm):
    def clean_email(self):
        data = self.cleaned_data['email']
        if "@" not in data:
            raise ValidationError("이메일 형식과 다릅니다.")

        return data
    
    class Meta:
        model = User
        fields = [
            'nickname', 'email'#, 'password'
            ]
        
class CheckForm(ModelForm):
    def clean_email(self):
        data = self.cleaned_data['email']
        if "@" not in data:
            raise ValidationError("이메일 형식과 다릅니다.")

        return data
    
    class Meta:
        model = User
        fields = [
            'email'#, 'password'
            ]
    
class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = [
            'title'
            ]

class UserInRoomForm(ModelForm):
    class Meta:
        model = UserInRoom
        fields = [
            'room_num', 'user_num'
            ]

class CalendarForm(ModelForm):
    class Meta:
        model = Calendar
        fields = [
            'category', 'title', 'schedule', 'coworker', 'start_date', 'end_date'#, 'room_num', 'user_num', 
            ]
        widgets = {
            # 'room_num': TextInput(attrs={'ghost':''}),
            # 'user_num': TextInput(attrs={'ghost':''}),
            'schedule': Textarea(attrs={'rows': 10}),
            'start_date': DateTimeInput(attrs={'type': 'datetime-local'}),
            'end_date': DateTimeInput(attrs={'type': 'datetime-local'}),
        }
    # def clean_coworker(self):
    #     data = self.cleaned_data['coworker']
    #     if "," in data:
    #         raise forms.ValidationError("콤마 멈춰!")

    #     return data

room/views.py
from django.shortcuts import render, redirect
from rest_framework.decorators import api_view
from scheduler.models import Room, UserInRoom, User
from scheduler.forms import RoomForm

def path_type(request):
    if request.path.split('/')[-1] == 'room':
        return 'Room'
    elif str.isdecimal(request.path.split('/')[-1]) and request.path.split('/')[-2] == 'enter':
        return 'scheduler'

# Create your views here.
@api_view(['POST'])
def join_room(request, room_num):
    user_num = request.POST['user_num']
    
    if UserInRoom.objects.filter(room_num=room_num, user_num=user_num).exists():
        return redirect('/')
    
    user_in_room = UserInRoom(
        user_num = user_num,
        room_num = room_num
    )
    
    user_in_room.save()
    
    return redirect('/?success=2')

@api_view(['POST'])
def out_room(request, room_num):
    user_num = request.POST['user_num']
    
    UserInRoom.objects.filter(room_num=room_num, user_num=user_num).delete()
    
    return redirect('/?success=3')
    
@api_view(['GET', 'POST'])
def create(request):
    if request.method == 'GET':
        roomForm = RoomForm
        context = {
            'path_type': path_type(request),
            'roomForm': roomForm
        }
        return render(request, 'scheduler/room/edit.html', context)
    elif request.method == 'POST':
        title = request.POST['title']
        master = request.POST['master']
        invite = list(map(str.strip, request.POST['invite'].split(',')))
        
        users = User.objects.filter(nickname__in=invite)
        
        users_num = list(filter(lambda z: z != int(master), list(map(lambda x: x.get('num'), users.values()))))
        
        print(users_num)
        
        room = Room(
            master=master,
            title=title,
        )

        room.save()
        
        userInRoom = UserInRoom(
            room_num_id=room.pk,
            user_num_id=master,
        )
        userInRoom.save()
        
        for i in users_num:
            UserInRoom(
                room_num_id=room.pk,
                user_num_id=i
            ).save()
        
        return redirect('/')
    
@api_view(['GET', 'POST'])
def edit(request, room_num):
    room = Room.objects.get(num=room_num)
    
    if request.method == 'POST':
        if not request.POST['master']:
            return redirect('/?error=4')
        room.title = request.POST['title']
        room.master = request.POST['master']
        room.save()
        
        invite = list(map(str.strip, request.POST['invite'].split(',')))
        
        users = User.objects.filter(nickname__in=invite)
        
        users_num = list(map(lambda x: x.get('num'), users.values()))
        
        for i in users_num:
            UserInRoom(
                room_num_id=room.pk,
                user_num_id=i
            ).save()
        
        return redirect('scheduler:index')
    else:
        if Room.objects.filter(num=room_num).exists():
            context = {
                'roomForm': RoomForm(instance=room),
                'room': room
            }
            return render(request, 'scheduler/room/edit.html', context)
        else: return redirect('/?error=3')

@api_view(['POST'])
def delete(request, room_num):
    room = Room.objects.filter(num=room_num)
    
    uir = UserInRoom.objects.filter(room_num=room_num)
    
    if room.exists(): room.delete()
    if uir.exists(): uir.delete()
    
    return redirect('scheduler:index')
    
@api_view(['GET'])
def enter_room(request, room_num):
    
    context = {
        'path_type': path_type(request),
        'room_num': room_num
    }
    
    return render(request, 'scheduler/schedule.html', context)

scheduler/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
# from django.utils import timezone
from rest_framework.decorators import api_view
from .forms import CalendarForm
from .models import User, Room, Calendar
from django.core import serializers
from django.http import JsonResponse, HttpResponse

# from django.contrib.auth import views as auth_views

def path_type(request):
    if request.path.split('/')[-1] == '':
        return 'Home'
    elif request.path.split('/')[-1] == 'schedule':
        return 'Schedule'
    
@api_view(['GET'])
def index(request):
    room_list = Room.objects.order_by('regdate')
    context = {
        'path_type': path_type(request),
        'room_list': room_list,
    }
    
    return render(request, 'scheduler/index.html', context)

@api_view(['GET'])
def schedule(request):
    user = User.objects.all()

    context = {
        'path_type': path_type(request),
        'schedule': user
    }

    return render(request, 'scheduler/schedule.html', context)

def calendar_list(reqeust, num):
    '''
    schedule 목록
    '''
    schedule_list = Calendar.objects.filter(room_num_id=num).order_by('regdate')
    
    # 밑에 과정들
    # https://dev-yakuza.posstree.com/ko/django/response-model-to-json/ [ 참조 ]
    
    list = serializers.serialize('json', schedule_list)
    return HttpResponse(list, content_type="text/json-comment-filtered")

def list(reqeust):
    '''
    schedule 목록
    '''
    schedule_list = Calendar.objects.order_by('regdate')
    context = {'schedule_list': schedule_list}
    return render(reqeust, 'scheduler/scheduler/list.html', context)

def create(request):
    '''
    schedule 등록
    '''
    if request.method == 'POST':
        form = CalendarForm(request.POST)
        if form.is_valid():
            calendar = form.save(commit=False)
            
            # modelForm에 해당되지 않는 필드는 자동 할당되지 않는다.
            # 수동으로 할당해야하고, 그러지 않으면 null값을 할당한다.
            calendar.room_num_id = request.POST['room_num']
            calendar.user_num = request.POST['user_num']
            
            calendar.start_date = str(calendar.start_date).replace('+09:00','+00:00')
            calendar.end_date = str(calendar.end_date).replace('+09:00','+00:00')
            
            calendar.save()
            
            return redirect ('room:enter', room_num=calendar.room_num_id)
    else:
        form = CalendarForm()
    context = {'form': form}
    return render(request, 'scheduler/scheduler/create.html', context)

def detail(request, schedule_num):
    '''
    schedule 내용 출력
    '''
    schedule = Calendar.objects.filter(pk=schedule_num).get(pk=schedule_num)
    context = {'schedule': schedule}
    return render(request, 'scheduler/scheduler/detail.html', context)

def update(request, schedule_num):
    '''
    schedule 내용 수정
    '''
    calendar = Calendar.objects.filter(pk=schedule_num).get(pk=schedule_num)
    if request.method == 'POST':
        form = CalendarForm(request.POST, instance=calendar)
        if form.is_valid():
            calendar = form.save(commit=False)
            calendar.save()
            return redirect ('room:enter', room_num=calendar.room_num_id)
    else:
        form = CalendarForm(instance=calendar)
    print(calendar.start_date)
    context = {'form': form, 'calendar':calendar}
    return render(request, 'scheduler/scheduler/update.html', context)

@api_view(['POST'])
def delete(request, schedule_num):
    '''
    schedule 삭제
    '''
    cal = Calendar.objects.filter(pk=schedule_num)
    
    room_num = cal[0].room_num_id
    
    cal.delete()
    
    return redirect('room:enter', room_num=room_num)

scheduler/templates/scheduler/room/create.html
{% extends '../layout.html' %}
{% load bootstrap5 %}
{% block content %}
<div class="container-fluid">
    
    <form action="{% url 'room:create' %}" method="post">
        {% bootstrap_form roomForm %}
        <input name="master" type="number" ghost value="{{request.session.sign.num}}">
        <button class="btn btn-info" type="submit">Create Room</button>
    </form>

</div>
{% endblock content %}

scheduler/templates/scheduler/room/edit.html
{% extends '../layout.html' %}
{% load customs %}
{% load bootstrap5 %}
{% block content %}
<div class="container-fluid">
    {% set request.path|split:'/'|arr_trim:''|last as rnum %}
    {% if rnum|is_number %}
    <form action="{% url 'room:create' %}" method="post">
    {% else %}
    <form action="{% url 'room:edit' room_num=room.num %}" method="post">
    {% endif %}
        {% bootstrap_form roomForm %}
        
        <div class="mb-3"><label class="form-label" for="id_title">Invite</label>
            <input type="text" name="invite" value="" maxlength="100" class="mb-3 form-control" placeholder='초대 인원을 ","로 구분해서 작성해주세요.' title="" id="invite">
            <div id="alert-info"></div>
        </div>

        {% if not rnum|is_number %}
        <div class="mb-5">
            <span class="badge bg-info">참여인원</span>
            {% for user in rnum|room_user|to_nickname %}
            <span class="badge text-dark">{{user}}</span>
            {% endfor %}
        </div>
        {% endif %}

        <script>
            invite.addEventListener('input', e=>{
                let users = invite.value.split(',').map(x=>x.trim()).filter(x=>x);
                axios({
                    method: 'get',
                    url: '/common/finduser',
                    params: {
                        userlist: JSON.stringify(users)
                    },
                }).then(res=>{
                    let target = document.querySelector('#alert-info');
                    let temp = '';
                    const render = (type, isuser) => {
                        // setTimeout(()=>{
                        //     if(temp==target.innerHTML)
                        //     target.innerHTML = '';
                        // }, 3000);
                        if(type == -1) {
                            target.innerHTML = '';
                            return;
                        }
                        if(type == 1){
                            target.innerHTML = `<div class="alert alert-info">모든 초대 인원의 정보가 확인 되었습니다.</div>`;
                        } else if(type == 0){
                            target.innerHTML = `<div class="alert alert-danger">확인되지 않은 회원 정보가 존재합니다. 다시 한 번 확인하시기 바랍니다.</div>`;
                        } else if(type == -1){
                            target.innerHTML = ``;
                        } else if(type == -2){
                            target.innerHTML = `<div class="alert alert-warning">${isuser}님은 이미 방에 참여하고 있습니다.</div>`;
                        }
                        
                        temp = target.innerHTML;
                    }

                    {% if rnum|is_number %}
                    let is_users = [];
                    let room_users = false;
                    {% else %}
                    let is_users = res.data.map(x=>x.fields.nickname);
                    let room_users = '{{rnum|room_user|to_nickname|join:','}}'.split(',');
                    {% endif %}

                    let nosubmit = false;
                    if(res.data.length != users.length){
                        render(0);
                        nosubmit = true;
                    } else if(room_users && room_users.filter(a=>is_users.indexOf(a)>-1).length){
                        let filtered = room_users.filter(a=>is_users.indexOf(a)>-1);
                        render(-2, filtered);
                        nosubmit = true;
                    } else if(res.data == 0) {
                        render(-1);
                        nosubmit = false;
                    } else {
                        render(1);
                        nosubmit = false;
                    }

                    if(nosubmit) edit.disabled = true;
                    else edit.removeAttribute('disabled')
                })
            });
        </script>
        
        <input name="master" type="number" ghost value="{{request.session.sign}}">
        <button id="edit" class="btn btn-info" type="submit">Edit Room</button>
    </form>

</div>
{% endblock content %}