account/urls.py
from django.urls import path
from . import views
# from django.contrib.auth import views as auth_views

app_name = 'account'

urlpatterns = [
    path('auth_reset_pass', views.auth_reset_pass, name='auth_reset_pass'),
    path('finduser', views.find_user, name='finduser'),
    path('send_mail', views.send_mail, name='send_mail'),
    path('find', views.find, name='find'),
    path('reset_pass', views.reset_pass, name='reset_pass'),
    path('signin', views.signin, name='signin'),
    path('signup', views.signup, name = 'signup'),
    path('update/<int:num>', views.update, name = 'update'),
    path('signout', views.signout, name="signout"),
    path('unsign/<int:num>', views.unsign, name="unsign")
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('scheduler.urls')),
    path('common/', include('account.urls')),
    path('room/', include('room.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

room/urls.py
from django.urls import path
from . import views

app_name = 'room'

urlpatterns = [
    path('room', views.create, name='create'),
    path('room/<int:room_num>', views.edit, name='edit'),
    path('room/del/<int:room_num>', views.delete, name='delete'),
    path('join/<int:room_num>', views.join_room, name='join'),
    path('out/<int:room_num>', views.out_room, name='out'),
    path('enter/<int:room_num>', views.enter_room, name='enter'),
]

scheduler/urls.py
from django.urls import path
from . import views

app_name = 'scheduler'

urlpatterns = [
    path('create/', views.create, name = 'schedule_create'),
    path('list/', views.list, name = 'schedule_list'),
    path('list/<int:schedule_num>/', views.detail, name = 'schedule_detail'),
    path('list/update/<int:schedule_num>/', views.update, name = 'schedule_update'),
    path('list/delete/<int:schedule_num>/', views.delete, name = 'schedule_delete'),
    # ----------------------------------------------------------------------------
    path('', views.index, name = 'index'), # 첫 화면 일정 리스트
    path('schedule/', views.schedule, name = 'schedule'), # 달력 스케줄
    # ----------------------------------------------------------------------------
    # path('test/', views.test, name = 'test'), # 달력 스케줄
    path('calendar_list/<int:num>/', views.calendar_list, name = 'calendar_list'), # 달력 스케줄
]

scheduler/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class User(models.Model):
    num = models.AutoField(primary_key=True)
    # primary_key를 지정해줘야 ~~.id field error가 나지 않는다.
    profile = models.ImageField(upload_to="", null=True, blank=True)
    nickname = models.CharField(max_length=45, null=False, unique=True)
    email = models.CharField(max_length=45, null=False)
    password = models.CharField(max_length=45, null=False, blank=True)
    regdate = models.DateTimeField('created', default=timezone.now, editable=False, null=False, blank=False)
    updates = models.DateTimeField('updated', default=timezone.now, editable=False, null=False, blank=False)
    
class Room(models.Model):
    num = models.AutoField(primary_key=True)
    master = models.IntegerField(null=False)
    title = models.CharField(max_length=45, null=False)
    regdate = models.DateTimeField('created', default=timezone.now, editable=False, null=False, blank=False)
    updates = models.DateTimeField('updated', default=timezone.now, editable=False, null=False, blank=False)
    
class UserInRoom(models.Model):
    num = models.AutoField(primary_key=True)
    room_num = models.ForeignKey(Room, on_delete=models.CASCADE, db_column='room_num')
    user_num = models.ForeignKey(User, on_delete=models.CASCADE, db_column='user_num')
    regdate = models.DateTimeField('created', default=timezone.now, editable=False, null=False, blank=False)
    updates = models.DateTimeField('updated', default=timezone.now, editable=False, null=False, blank=False)
    
class Calendar(models.Model):
    num = models.AutoField(primary_key=True)
    room_num = models.ForeignKey(Room, on_delete=models.CASCADE, db_column='room_num')
    user_num = models.IntegerField(null=False)
    category = models.CharField(max_length=45, null=False)
    title = models.CharField(max_length=50, null=False)
    schedule = models.TextField(blank=True, null=True)
    coworker = models.CharField(max_length=200, null=False)
    start_date = models.DateTimeField('start', null=False, blank=False)
    end_date = models.DateTimeField('end', null=False, blank=False)
    regdate = models.DateTimeField('created', default=timezone.now, editable=False, null=False, blank=False)
    updates = models.DateTimeField('updated', default=timezone.now, editable=False, null=False, blank=False)

scheduler/forms.py
from django.forms import CharField, DateInput, DateTimeInput, EmailInput, FileInput, ImageField, ModelForm, PasswordInput, TextInput, Textarea, ValidationError
from .models import *

class UserForm(ModelForm):
    profile = ImageField(required=False, widget=FileInput(attrs={'type': 'file'}))
    password = CharField(required=False, widget=PasswordInput(attrs={'type': 'password', 'autocomplete': 'current-password'}))
    
    class Meta:
        model = User
        fields = [
            'profile', 'nickname', 'email', 'password'
            ]
        widgets = {
            'email': EmailInput(attrs={'autocomplete': 'username'}),
        }
        
class LoginForm(ModelForm):
    # email = forms.CharField(required=False)
    
    def clean_email(self):
        data = self.cleaned_data['email']
        if "@" not in data:
            raise ValidationError("이메일 형식과 다릅니다.")

        # Always return a value to use as the new cleaned data, even if
        # this method didn't change it.
        return data
    
    class Meta:
        model = User
        fields = [
            'email', 'password'
            ]
        widgets = {
            'email': EmailInput(attrs={'type':'email', 'autocomplete':'username'}),
            'password': PasswordInput(attrs={'type':'password', 'autocomplete':'current-password'})
        }
        
class FindForm(ModelForm):
    def clean_email(self):
        data = self.cleaned_data['email']
        if "@" not in data:
            raise ValidationError("이메일 형식과 다릅니다.")

        return data
    
    class Meta:
        model = User
        fields = [
            'nickname', 'email'#, 'password'
            ]
        
class CheckForm(ModelForm):
    def clean_email(self):
        data = self.cleaned_data['email']
        if "@" not in data:
            raise ValidationError("이메일 형식과 다릅니다.")

        return data
    
    class Meta:
        model = User
        fields = [
            'email'#, 'password'
            ]
    
class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = [
            'title'
            ]

class UserInRoomForm(ModelForm):
    class Meta:
        model = UserInRoom
        fields = [
            'room_num', 'user_num'
            ]

class CalendarForm(ModelForm):
    class Meta:
        model = Calendar
        fields = [
            'category', 'title', 'schedule', 'coworker', 'start_date', 'end_date'#, 'room_num', 'user_num', 
            ]
        widgets = {
            # 'room_num': TextInput(attrs={'ghost':''}),
            # 'user_num': TextInput(attrs={'ghost':''}),
            'schedule': Textarea(attrs={'rows': 10}),
            'start_date': DateTimeInput(attrs={'type': 'datetime-local'}),
            'end_date': DateTimeInput(attrs={'type': 'datetime-local'}),
        }
    # def clean_coworker(self):
    #     data = self.cleaned_data['coworker']
    #     if "," in data:
    #         raise forms.ValidationError("콤마 멈춰!")

    #     return data

scheduler/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
# from django.utils import timezone
from rest_framework.decorators import api_view
from .forms import CalendarForm
from .models import User, Room, Calendar
from django.core import serializers
from django.http import JsonResponse, HttpResponse

# from django.contrib.auth import views as auth_views

def path_type(request):
    if request.path.split('/')[-1] == '':
        return 'Home'
    elif request.path.split('/')[-1] == 'schedule':
        return 'Schedule'
    
@api_view(['GET'])
def index(request):
    room_list = Room.objects.order_by('regdate')
    context = {
        'path_type': path_type(request),
        'room_list': room_list,
    }
    
    return render(request, 'scheduler/index.html', context)

@api_view(['GET'])
def schedule(request):
    user = User.objects.all()

    context = {
        'path_type': path_type(request),
        'schedule': user
    }

    return render(request, 'scheduler/schedule.html', context)

def calendar_list(reqeust, num):
    '''
    schedule 목록
    '''
    schedule_list = Calendar.objects.filter(room_num_id=num).order_by('regdate')
    
    # 밑에 과정들
    # https://dev-yakuza.posstree.com/ko/django/response-model-to-json/ [ 참조 ]
    
    list = serializers.serialize('json', schedule_list)
    return HttpResponse(list, content_type="text/json-comment-filtered")

def list(reqeust):
    '''
    schedule 목록
    '''
    schedule_list = Calendar.objects.order_by('regdate')
    context = {'schedule_list': schedule_list}
    return render(reqeust, 'scheduler/scheduler/list.html', context)

def create(request):
    '''
    schedule 등록
    '''
    if request.method == 'POST':
        form = CalendarForm(request.POST)
        if form.is_valid():
            calendar = form.save(commit=False)
            
            # modelForm에 해당되지 않는 필드는 자동 할당되지 않는다.
            # 수동으로 할당해야하고, 그러지 않으면 null값을 할당한다.
            calendar.room_num_id = request.POST['room_num']
            calendar.user_num = request.POST['user_num']
            
            calendar.start_date = str(calendar.start_date).replace('+09:00','+00:00')
            calendar.end_date = str(calendar.end_date).replace('+09:00','+00:00')
            
            calendar.save()
            
            return redirect ('room:enter', room_num=calendar.room_num_id)
    else:
        form = CalendarForm()
    context = {'form': form}
    return render(request, 'scheduler/scheduler/create.html', context)

def detail(request, schedule_num):
    '''
    schedule 내용 출력
    '''
    schedule = Calendar.objects.filter(pk=schedule_num).get(pk=schedule_num)
    context = {'schedule': schedule}
    return render(request, 'scheduler/scheduler/detail.html', context)

def update(request, schedule_num):
    '''
    schedule 내용 수정
    '''
    calendar = Calendar.objects.filter(pk=schedule_num).get(pk=schedule_num)
    if request.method == 'POST':
        form = CalendarForm(request.POST, instance=calendar)
        if form.is_valid():
            calendar = form.save(commit=False)
            calendar.save()
            return redirect ('room:enter', room_num=calendar.room_num_id)
    else:
        form = CalendarForm(instance=calendar)
    print(calendar.start_date)
    context = {'form': form, 'calendar':calendar}
    return render(request, 'scheduler/scheduler/update.html', context)

@api_view(['POST'])
def delete(request, schedule_num):
    '''
    schedule 삭제
    '''
    cal = Calendar.objects.filter(pk=schedule_num)
    
    room_num = cal[0].room_num_id
    
    cal.delete()
    
    return redirect('room:enter', room_num=room_num)

scheduler/templates/scheduler/common/aside.html
<aside class="left-sidebar" data-sidebarbg="skin6">
    <div class="scroll-sidebar">
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href="/" aria-expanded="false">
                        <i class="mdi mdi-view-dashboard"></i>
                        <span class="hide-menu">List</span>
                    </a>
                </li>
                {% if request.session.sign %}
                <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'account:signout' %}" aria-expanded="false">
                        <i class="mdi mdi-export"></i>
                        <span class="hide-menu">sign out</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'account:update' num=request.session.sign %}" aria-expanded="false">
                        <i class="mdi mdi-account-circle"></i>
                        <span class="hide-menu">User Info</span>
                    </a>
                </li>
                {% else %}
                <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'account:signin' %}" aria-expanded="false">
                        <i class="mdi mdi-import"></i>
                        <span class="hide-menu">Sign in</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'account:signup' %}" aria-expanded="false">
                        <i class="mdi mdi-account-multiple-plus"></i>
                        <span class="hide-menu">Sign up</span>
                    </a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</aside>

scheduler/templates/scheduler/common/breadcrumb.html
<div class="page-breadcrumb">
    <div class="row align-items-center">
        <div class="col-12">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb mb-0 d-flex align-items-center">
                <li class="breadcrumb-item"><a href="/" class="link"><i class="mdi mdi-home-outline fs-4"></i></a></li>
                <li class="breadcrumb-item active" aria-current="page">
                    {{path_type}}
                </li>
                </ol>
            </nav>
            <h1 class="mb-0 fw-bold">{{path_type}}</h1> 
        </div>
    </div>
</div>

scheduler/templates/scheduler/common/load-scripts.html
{% load static %}
<script src="{% static 'assets/libs/jquery/dist/jquery.min.js' %}"></script>
<!-- Bootstrap tether Core JavaScript -->
<script src="{% static 'assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'dist/js/app-style-switcher.js' %}"></script>
<!--Wave Effects -->
<script src="{% static 'dist/js/waves.js' %}"></script>
<!--Menu sidebar -->
<script src="{% static 'dist/js/sidebarmenu.js' %}"></script>
<!--Custom JavaScript -->
<script src="{% static 'dist/js/custom.js' %}"></script>
<!--This page JavaScript -->
<!--chartis chart-->
<script src="{% static 'assets/libs/chartist/dist/chartist.min.js' %}"></script>
<script src="{% static 'assets/libs/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.min.js' %}"></script>
<script src="{% static 'dist/js/pages/dashboards/dashboard1.js' %}"></script>
<script src="{% static 'src/custom/script/main.js' %}"></script>

scheduler/templates/scheduler/common/load-styles.html
{% load static %}
{% load sass_tags %}

<link rel="canonical" href="https://www.wrappixel.com/templates/Flexy-admin-lite/" />
<!-- Favicon icon -->
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/images/favicon.png' %}">
<!-- Custom CSS -->
<link href="{% static 'assets/libs/chartist/dist/chartist.min.css' %}" rel="stylesheet">
<link href="{% static 'assets/libs/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.css' %}" rel="stylesheet">
<!-- Custom CSS -->
<link href="{% sass_src 'src/custom/scss/custom.scss' %}" rel="stylesheet">
<link rel="stylesheet" href="{% sass_src 'src/scss/style.scss' %}">
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>-->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar@5.10.2/main.min.css">

<!-- calendar -->

<script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.10.2/main.min.js"></script>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        var calendarEl = document.getElementById('calendar');
        var calendar = new FullCalendar.Calendar(calendarEl, {
          initialView: 'dayGridMonth'
        });
        if(location.href.match(/schedule/g))
        setTimeout(()=>{
            calendar.render();
        }, 100);
      });
</script>

{% comment %} fullcalendar {% endcomment %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar@5.10.2/main.min.css">
<script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.10.2/main.min.js"></script>
<script src="{% static 'src/custom/script/calendar.js' %}"></script>

{% comment %} axios {% endcomment %}
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

scheduler/templates/scheduler/common/nav.html
{% load static %}
{% load customs %}

{% set request.session.sign|user_profile:'https://images.theconversation.com/files/443350/original/file-20220131-15-1ndq1m6.jpg?ixlib=rb-1.1.0&rect=0%2C0%2C3354%2C2464&q=45&auto=format&w=926&fit=clip' as profile %}
{% firstof '' request.session.sign|user_nickname as nickname %}

<header class="topbar" data-navbarbg="skin6">
    <nav class="navbar top-navbar navbar-expand-md navbar-light">
        <div class="navbar-header" data-logobg="skin6">
            <a class="navbar-brand" href="/">
                <b class="logo-icon">
                    <img src="{% static 'assets/images/logo-icon.png' %}" alt="homepage" class="dark-logo" />
                    <img src="{% static 'assets/images/logo-light-icon.png' %}" alt="homepage" class="light-logo" />
                </b>
                <span class="logo-text">
                    <img src="{% static 'assets/images/logo-text.png' %}" alt="homepage" class="dark-logo" />
                    <img src="{% static 'assets/images/logo-light-text.png' %}" class="light-logo" alt="homepage" />
                </span>
            </a>
            <a class="nav-toggler waves-effect waves-light d-block d-md-none" href="javascript:void(0)"><i
                    class="mdi mdi-menu"></i></a>
        </div>
        <div class="navbar-collapse collapse" id="navbarSupportedContent" data-navbarbg="skin5">
            <ul class="navbar-nav float-start me-auto">
                <li class="nav-item search-box"> <a class="nav-link waves-effect waves-dark"
                        href="javascript:void(0)"><i class="mdi mdi-magnify me-1"></i> <span class="font-16">Search</span></a>
                    <form class="app-search position-absolute">
                        <input type="text" class="form-control" placeholder="Search &amp; enter"> <a
                            class="srh-btn"><i class="mdi mdi-window-close"></i></a>
                    </form>
                </li>
            </ul>
            <ul class="navbar-nav float-end">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-muted waves-effect waves-dark pro-pic" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="{{profile}}" alt="user" class="rounded-circle" width="31" height="31" style="aspect-ratio: 6/6">
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end user-dd animated" aria-labelledby="navbarDropdown">
                        {% if request.session.sign %}
                        <a class="dropdown-item" href="{% url 'account:update' request.session.sign %}"><i class="ti-user m-r-5 m-l-5"></i>
                            {{nickname}}님</a>
                        {% endif %}
                        <a class="dropdown-item" href="javascript:void(0)"><i class="ti-wallet m-r-5 m-l-5"></i>
                            My Balance</a>
                        <a class="dropdown-item" href="javascript:void(0)"><i class="ti-email m-r-5 m-l-5"></i>
                            Inbox</a>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

scheduler/templates/scheduler/common/toast.html
<div aria-live="polite" aria-atomic="true" class="position-fixed w-100 bottom-0">
  <!-- Position it: -->
  <!-- - `.toast-container` for spacing between toasts -->
  <!-- - `.position-absolute`, `top-0` & `end-0` to position the toasts in the upper right corner -->
  <!-- - `.p-3` to prevent the toasts from sticking to the edge of the container  -->
  <div class="toast-container position-absolute bottom-0 end-0 p-3">

    <!-- Then put toasts within -->
    
  </div>
</div>